default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

server: &server
  username: maksim
  password: 1011
  host: localhost
  port: 5432

development:
  <<: *default
  <<: *server
  database: remove-it_development

test:
  <<: *default
  <<: *server
  database: remove-it_test

production:  
  <<: *default
  username: root
  password: 
  url: <%= ENV['DATABASE_URL'] %>
